export const RECIPES_LIST_REQUEST = 'RECIPES_LIST_REQUEST';
export const RECIPES_LIST_RECEIVED = 'RECIPES_LIST_RECEIVED';
export const RECIPES_LIST_ERROR = 'RECIPES_LIST_ERROR';
export const RECIPES_LIST_ADD = 'RECIPES_LIST_ADD';

export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_RECEIVED = 'RECIPES_RECEIVED';
export const RECIPES_ERROR = 'RECIPES_ERROR';
export const RECIPES_UNLOAD = 'RECIPES_UNLOAD';