export const RECIPES_LIST_REQUEST = 'RECIPES_LIST_REQUEST';
export const RECIPES_LIST_RECEIVED = 'RECIPES_LIST_RECEIVED';
export const RECIPES_LIST_ERROR = 'RECIPES_LIST_ERROR';
export const RECIPES_LIST_ADD = 'RECIPES_LIST_ADD';

export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_RECEIVED = 'RECIPES_RECEIVED';
export const RECIPES_ERROR = 'RECIPES_ERROR';
export const RECIPES_UNLOAD = 'RECIPES_UNLOAD';

export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_RECEIVED = 'COMMENTS_LIST_RECEIVED';
export const COMMENTS_LIST_ERROR = 'COMMENTS_LIST_ERROR';
export const COMMENTS_LIST_UNLOAD = 'COMMENTS_LIST_UNLOAD';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';