export const RECIPES_LIST_REQUEST = 'RECIPES_LIST_REQUEST';
export const RECIPES_LIST_RECEIVED = 'RECIPES_LIST_RECEIVED';
export const RECIPES_LIST_ERROR = 'RECIPES_LIST_ERROR';
export const RECIPES_LIST_ADD = 'RECIPES_LIST_ADD';
export const RECIPES_LIST_SET_PAGE = 'RECIPES_LIST_SET_PAGE';

export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_RECEIVED = 'RECIPES_RECEIVED';
export const RECIPES_ERROR = 'RECIPES_ERROR';
export const RECIPES_UNLOAD = 'RECIPES_UNLOAD';

export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_RECEIVED = 'COMMENTS_LIST_RECEIVED';
export const COMMENTS_LIST_ERROR = 'COMMENTS_LIST_ERROR';
export const COMMENTS_LIST_UNLOAD = 'COMMENTS_LIST_UNLOAD';

export const COMMENT_ADDED = 'COMMENTS_ADDED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
